/*******************************************************************************
 * Copyright (c) 2010 Michal Antkiewicz.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Michal Antkiewicz - initial API and implementation
 ******************************************************************************/
/**
  *
 *
 *
 * $Id: AdapterRequestorValidator.java,v 1.2 2007/12/05 16:18:43 Michal Antkiewicz <mantkiew@gsd.uwaterloo.ca> $
 */
package ca.uwaterloo.gsd.wpi.validation;

import org.eclipse.emf.common.util.EList;

import ca.uwaterloo.gsd.wpi.Part;
import ca.uwaterloo.gsd.wpi.RequestsAdapter;

/**
 * A sample validator interface for {@link ca.uwaterloo.gsd.wpi.AdapterRequestor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdapterRequestorValidator {
	boolean validate();

	boolean validateAdapterRequestor(Part value);
	boolean validateRequestsAdapter(EList<RequestsAdapter> value);
}
